import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import getConfig from 'next/config';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { publicRuntimeConfig } = getConfig();
  const version = publicRuntimeConfig?.version
  return (
    <html lang="en">
      <body className={inter.className}>{version}{children}</body>
    </html>
  )
}
